//! Generated by `bun scripts/bundle-accepted-contracts.mjs`. Do not edit.
//!
//! The bytes of every object named by `pkg/contracts/accepted/index.json`,
//! compiled in beside the index so a bundle is one reviewable pair of files in
//! the repository rather than a blob inside another document.

pub(super) const OBJECTS: &[(&str, &[u8])] = &[];
