[workspace]
members = ["crates/typefacts"]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT"
publish = true
rust-version = "1.97"
version = "0.2.0"

[workspace.dependencies]
ciborium = "0.2.2"
serde = { version = "1.0.219", features = ["derive", "rc"] }
serde_bytes = "0.11.15"
sha2 = "0.10.9"
thiserror = "2.0.12"
