//! Where `@solidjs/web@2.0.0-rc.0` exports each name, keyed by the module specifier a
//! user writes in an import.
//!
//! Audited against the exact `@solidjs/web@2.0.0-rc.3` published declaration surface.
//!
//! Sorted by name so lookup can binary search. A name appears under every
//! module that exports it — 1.x's `solid-js/web` re-exports nine control-flow
//! components from `solid-js`, and importing one of them from either module
//! resolves.

/// Names exported in value position.
#[rustfmt::skip]
pub static VALUES: &[(&str, &[&str])] = &[
    ("ChildProperties", &["@solidjs/web"]),
    ("ChunkReader", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client"]),
    ("DEFAULT_WEB_PLUGINS", &["@solidjs/web/serialization", "@solidjs/web/serialization/decode"]),
    ("DOMElements", &["@solidjs/web"]),
    ("DOMWithState", &["@solidjs/web"]),
    ("DelegatedEvents", &["@solidjs/web"]),
    ("Dynamic", &["@solidjs/web"]),
    ("ERROR_HEADER", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client", "@solidjs/web/server-functions/server"]),
    ("Errored", &["@solidjs/web"]),
    ("FLASH_COOKIE", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client", "@solidjs/web/server-functions/server"]),
    ("FRAME_APPLIED_EVENT", &["@solidjs/web/frames", "@solidjs/web/frames/client"]),
    ("FRAME_STREAM_HEADER", &["@solidjs/web/frames", "@solidjs/web/frames/client", "@solidjs/web/frames/server"]),
    ("FUNCTION_HEADER", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client", "@solidjs/web/server-functions/server"]),
    ("For", &["@solidjs/web"]),
    ("GENERIC_SERVER_ERROR_MESSAGE", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/server"]),
    ("GET", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client", "@solidjs/web/server-functions/server"]),
    ("HREF", &["@solidjs/web"]),
    ("Hydration", &["@solidjs/web"]),
    ("HydrationScript", &["@solidjs/web"]),
    ("INSTANCE_HEADER", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client", "@solidjs/web/server-functions/server"]),
    ("Loading", &["@solidjs/web"]),
    ("Match", &["@solidjs/web"]),
    ("MathMLElements", &["@solidjs/web"]),
    ("Namespaces", &["@solidjs/web"]),
    ("NoHydration", &["@solidjs/web"]),
    ("OpaqueReference", &["@solidjs/web/serialization"]),
    ("Portal", &["@solidjs/web"]),
    ("REVALIDATE_HEADER", &["@solidjs/web", "@solidjs/web/server-functions", "@solidjs/web/server-functions/client"]),
    ("RawTextElements", &["@solidjs/web"]),
    ("Repeat", &["@solidjs/web"]),
    ("RequestContext", &["@solidjs/web"]),
    ("ResponseEnvelope", &["@solidjs/web"]),
    ("Reveal", &["@solidjs/web"]),
    ("SAFE_ERROR", &["@solidjs/web"]),
    ("SERVER_COMPONENT_BOOTSTRAP", &["@solidjs/web/frames", "@solidjs/web/frames/server"]),
    ("SINGLE_FLIGHT_HEADER", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client", "@solidjs/web/server-functions/server"]),
    ("SVGElements", &["@solidjs/web"]),
    ("ServerComponentPlugin", &["@solidjs/web/frames", "@solidjs/web/frames/server"]),
    ("Show", &["@solidjs/web"]),
    ("Switch", &["@solidjs/web"]),
    ("VoidElements", &["@solidjs/web"]),
    ("acquireAsset", &["@solidjs/web"]),
    ("addEvent", &["@solidjs/web"]),
    ("applyFrameResponse", &["@solidjs/web/frames", "@solidjs/web/frames/client"]),
    ("applyRef", &["@solidjs/web"]),
    ("assign", &["@solidjs/web"]),
    ("asyncArg", &["@solidjs/web/frames", "@solidjs/web/frames/client", "@solidjs/web/frames/server"]),
    ("claimElement", &["@solidjs/web"]),
    ("claimElementTree", &["@solidjs/web"]),
    ("className", &["@solidjs/web"]),
    ("clearFlashCookie", &["@solidjs/web", "@solidjs/web/server-functions", "@solidjs/web/server-functions/client", "@solidjs/web/server-functions/server"]),
    ("clientOnly", &["@solidjs/web"]),
    ("commitEventResponse", &["@solidjs/web"]),
    ("composeMiddleware", &["@solidjs/web"]),
    ("configureServerFunctionsClient", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client"]),
    ("configureServerFunctionsServer", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/server"]),
    ("createChunk", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client"]),
    ("createComponent", &["@solidjs/web"]),
    ("createFrame", &["@solidjs/web/frames", "@solidjs/web/frames/client"]),
    ("createFrameElement", &["@solidjs/web/frames", "@solidjs/web/frames/client"]),
    ("createFrameHost", &["@solidjs/web/frames", "@solidjs/web/frames/client"]),
    ("createFrameSink", &["@solidjs/web/frames", "@solidjs/web/frames/server"]),
    ("createHydrationSerializer", &["@solidjs/web/serialization"]),
    ("createJSONDataTable", &["@solidjs/web/serialization", "@solidjs/web/serialization/decode"]),
    ("createJSONDeserializer", &["@solidjs/web/serialization", "@solidjs/web/serialization/decode"]),
    ("createJSONSerializer", &["@solidjs/web/serialization"]),
    ("createNoJSHandler", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/server"]),
    ("createPlugin", &["@solidjs/web/serialization"]),
    ("createRequestEvent", &["@solidjs/web"]),
    ("createResponseStub", &["@solidjs/web"]),
    ("createSSRResponse", &["@solidjs/web"]),
    ("createSerializer", &["@solidjs/web/serialization"]),
    ("createServerComponentHandler", &["@solidjs/web/frames", "@solidjs/web/frames/client"]),
    ("createServerReference", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client", "@solidjs/web/server-functions/server"]),
    ("decodeErrorHeaderValue", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client", "@solidjs/web/server-functions/server"]),
    ("decodeFlashCookie", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/server"]),
    ("decodeResponse", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client", "@solidjs/web/server-functions/server"]),
    ("decodeResponsePayload", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client", "@solidjs/web/server-functions/server"]),
    ("delegateEvents", &["@solidjs/web"]),
    ("deserializeStream", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client"]),
    ("dynamic", &["@solidjs/web"]),
    ("dynamicProperty", &["@solidjs/web"]),
    ("effect", &["@solidjs/web"]),
    ("enableRichArguments", &["@solidjs/web/server-functions/rich-args"]),
    ("encodeErrorHeaderValue", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client", "@solidjs/web/server-functions/server"]),
    ("encodeFlashCookie", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/server"]),
    ("escape", &["@solidjs/web"]),
    ("foldSetCookies", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/server"]),
    ("frameAddress", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client"]),
    ("frameTransformDirectResult", &["@solidjs/web/frames", "@solidjs/web/frames/server"]),
    ("frameTransformFlightResult", &["@solidjs/web/frames", "@solidjs/web/frames/server"]),
    ("frameTransformResult", &["@solidjs/web/frames", "@solidjs/web/frames/server"]),
    ("generateHydrationScript", &["@solidjs/web"]),
    ("getDelegatedRoot", &["@solidjs/web"]),
    ("getEventServerFunctionInvocation", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/server"]),
    ("getExpectedRedirectStatus", &["@solidjs/web"]),
    ("getFlightDataConsumer", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client"]),
    ("getFrameHost", &["@solidjs/web/frames", "@solidjs/web/frames/client"]),
    ("getHydrationKey", &["@solidjs/web"]),
    ("getLocalHeaderScript", &["@solidjs/web/serialization"]),
    ("getNextElement", &["@solidjs/web"]),
    ("getNextMarker", &["@solidjs/web"]),
    ("getNextMatch", &["@solidjs/web"]),
    ("getOwner", &["@solidjs/web"]),
    ("getRequestEvent", &["@solidjs/web"]),
    ("getServerFunction", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/server"]),
    ("getServerFunctionInvocation", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client", "@solidjs/web/server-functions/server"]),
    ("getServerFunctionMetadata", &["@solidjs/web", "@solidjs/web/server-functions", "@solidjs/web/server-functions/client", "@solidjs/web/server-functions/server"]),
    ("getServerFunctionRPC", &["@solidjs/web"]),
    ("getServerFunctionsCodec", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client"]),
    ("handleServerFunctionRequest", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/server"]),
    ("hasFlashCookie", &["@solidjs/web", "@solidjs/web/server-functions", "@solidjs/web/server-functions/client", "@solidjs/web/server-functions/server"]),
    ("httpHeader", &["@solidjs/web"]),
    ("httpStatus", &["@solidjs/web"]),
    ("hydrate", &["@solidjs/web"]),
    ("insert", &["@solidjs/web"]),
    ("installServerComponents", &["@solidjs/web/frames", "@solidjs/web/frames/client"]),
    ("isDev", &["@solidjs/web"]),
    ("isFrameStreamResponse", &["@solidjs/web/frames", "@solidjs/web/frames/client", "@solidjs/web/frames/server"]),
    ("isHref", &["@solidjs/web"]),
    ("isResponseEnvelope", &["@solidjs/web"]),
    ("isSafeError", &["@solidjs/web"]),
    ("isServer", &["@solidjs/web"]),
    ("isServerFunction", &["@solidjs/web", "@solidjs/web/server-functions", "@solidjs/web/server-functions/client", "@solidjs/web/server-functions/server"]),
    ("markSafeError", &["@solidjs/web"]),
    ("memo", &["@solidjs/web"]),
    ("mergeProps", &["@solidjs/web"]),
    ("parseCookieHeader", &["@solidjs/web"]),
    ("provideRequestEvent", &["@solidjs/web/storage"]),
    ("redirect", &["@solidjs/web"]),
    ("ref", &["@solidjs/web"]),
    ("registerDelegatedContainer", &["@solidjs/web"]),
    ("registerDelegatedRoot", &["@solidjs/web"]),
    ("registerElementClaim", &["@solidjs/web"]),
    ("registerServerFunction", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/server"]),
    ("registerServerReference", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client", "@solidjs/web/server-functions/server"]),
    ("reload", &["@solidjs/web"]),
    ("render", &["@solidjs/web"]),
    ("renderServerComponent", &["@solidjs/web/frames", "@solidjs/web/frames/server"]),
    ("renderToFrameStream", &["@solidjs/web/frames", "@solidjs/web/frames/server"]),
    ("renderToStream", &["@solidjs/web"]),
    ("renderToString", &["@solidjs/web"]),
    ("resolveSSRNode", &["@solidjs/web"]),
    ("resolveSerializerPlugins", &["@solidjs/web/serialization", "@solidjs/web/serialization/decode"]),
    ("respond", &["@solidjs/web"]),
    ("runHydrationEvents", &["@solidjs/web"]),
    ("sanitizeServerError", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/server"]),
    ("scope", &["@solidjs/web"]),
    ("serializeCookie", &["@solidjs/web"]),
    ("serializeJSON", &["@solidjs/web/serialization"]),
    ("serializeString", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client"]),
    ("serverComponentResponse", &["@solidjs/web/frames", "@solidjs/web/frames/server"]),
    ("setAttribute", &["@solidjs/web"]),
    ("setAttributeNS", &["@solidjs/web"]),
    ("setProperty", &["@solidjs/web"]),
    ("setServerFunctionsDev", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/server"]),
    ("setStyleProperty", &["@solidjs/web"]),
    ("spread", &["@solidjs/web"]),
    ("ssr", &["@solidjs/web"]),
    ("ssrAttribute", &["@solidjs/web"]),
    ("ssrClassName", &["@solidjs/web"]),
    ("ssrElement", &["@solidjs/web"]),
    ("ssrGroup", &["@solidjs/web"]),
    ("ssrHydrationKey", &["@solidjs/web"]),
    ("ssrStyle", &["@solidjs/web"]),
    ("ssrStyleProperty", &["@solidjs/web"]),
    ("style", &["@solidjs/web"]),
    ("subscribeFlightData", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client", "@solidjs/web/server-functions/server"]),
    ("template", &["@solidjs/web"]),
    ("unregisterDelegatedContainer", &["@solidjs/web"]),
    ("unregisterDelegatedRoot", &["@solidjs/web"]),
    ("untrack", &["@solidjs/web"]),
    ("useHead", &["@solidjs/web"]),
    ("warmAsset", &["@solidjs/web"]),
    ("withMeta", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client", "@solidjs/web/server-functions/server"]),
];

/// Names exported in type position. Disjoint from [`VALUES`] only by
/// accident: a class is both, and appears in each.
#[rustfmt::skip]
pub static TYPES: &[(&str, &[&str])] = &[
    ("AssetDescriptor", &["@solidjs/web"]),
    ("AssetEntry", &["@solidjs/web"]),
    ("AssetManifest", &["@solidjs/web"]),
    ("AssetResolver", &["@solidjs/web"]),
    ("AssetResolverFn", &["@solidjs/web"]),
    ("AsyncParsePluginContext", &["@solidjs/web/serialization", "@solidjs/web/serialization/decode"]),
    ("ClassValue", &["@solidjs/web/jsx-dev-runtime", "@solidjs/web/jsx-runtime"]),
    ("CollectFlightDataHook", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/server"]),
    ("ComponentProps", &["@solidjs/web"]),
    ("CookieOptions", &["@solidjs/web"]),
    ("DeserializePluginContext", &["@solidjs/web/serialization", "@solidjs/web/serialization/decode"]),
    ("DynamicProps", &["@solidjs/web"]),
    ("ExclusiveAssetDescriptor", &["@solidjs/web"]),
    ("FetchMiddleware", &["@solidjs/web"]),
    ("FlashSubmission", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/server"]),
    ("FlightDataConsumer", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client", "@solidjs/web/server-functions/server"]),
    ("FlightDataContext", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client", "@solidjs/web/server-functions/server"]),
    ("HandleServerFunctionOptions", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/server"]),
    ("HeadTag", &["@solidjs/web"]),
    ("Href", &["@solidjs/web"]),
    ("HydrationSerializerOptions", &["@solidjs/web/serialization"]),
    ("InlineStyleAsset", &["@solidjs/web"]),
    ("IntrinsicElement", &["@solidjs/web"]),
    ("JSONCodecOptions", &["@solidjs/web/serialization", "@solidjs/web/serialization/decode"]),
    ("JSONDataTable", &["@solidjs/web/serialization", "@solidjs/web/serialization/decode"]),
    ("JSONSerializeOptions", &["@solidjs/web/serialization"]),
    ("JSONSerializerOptions", &["@solidjs/web/serialization"]),
    ("JSX", &["@solidjs/web", "@solidjs/web/jsx-dev-runtime", "@solidjs/web/jsx-runtime"]),
    ("NoJSHandlerOptions", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/server"]),
    ("PluginData", &["@solidjs/web/serialization", "@solidjs/web/serialization/decode"]),
    ("PluginInfo", &["@solidjs/web/serialization", "@solidjs/web/serialization/decode"]),
    ("PrepareRequestContext", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client"]),
    ("PrepareRequestHook", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client"]),
    ("RequestEvent", &["@solidjs/web"]),
    ("RequestEventLocals", &["@solidjs/web"]),
    ("ResolvedAssets", &["@solidjs/web"]),
    ("ResponseHelperInit", &["@solidjs/web"]),
    ("ResponseStub", &["@solidjs/web"]),
    ("SerializePluginContext", &["@solidjs/web/serialization", "@solidjs/web/serialization/decode"]),
    ("SerializerPlugin", &["@solidjs/web/serialization", "@solidjs/web/serialization/decode"]),
    ("SerovalNode", &["@solidjs/web/serialization", "@solidjs/web/serialization/decode"]),
    ("ServerFunction", &["@solidjs/web", "@solidjs/web/server-functions", "@solidjs/web/server-functions/client", "@solidjs/web/server-functions/server"]),
    ("ServerFunctionEvent", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/server"]),
    ("ServerFunctionInvocation", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client", "@solidjs/web/server-functions/server"]),
    ("ServerFunctionMetadata", &["@solidjs/web", "@solidjs/web/server-functions", "@solidjs/web/server-functions/client", "@solidjs/web/server-functions/server"]),
    ("ServerFunctionOutcome", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/server"]),
    ("ServerFunctionRPC", &["@solidjs/web"]),
    ("ServerFunctionReference", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/server"]),
    ("ServerFunctionsClientConfig", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client"]),
    ("ServerFunctionsServerConfig", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/server"]),
    ("SingleFlightPayload", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/client", "@solidjs/web/server-functions/server"]),
    ("Slot", &["@solidjs/web/frames", "@solidjs/web/frames/client", "@solidjs/web/frames/server"]),
    ("StreamParsePluginContext", &["@solidjs/web/serialization", "@solidjs/web/serialization/decode"]),
    ("SyncParsePluginContext", &["@solidjs/web/serialization", "@solidjs/web/serialization/decode"]),
    ("ValidComponent", &["@solidjs/web"]),
    ("WebSerializerOptions", &["@solidjs/web/serialization"]),
    ("WrapInvocationHook", &["@solidjs/web/server-functions", "@solidjs/web/server-functions/server"]),
];
