export interface SourceFile {
  path: string
  source: string
  compilerOptions?: {
    moduleName: string
    generate: string
    hydratable?: boolean
    dev?: boolean
    effectWrapper?: string
    wrapConditionals?: boolean
    staticMarker?: string
    builtIns?: string[]
  }
}

export interface ResolvedFile {
  path: string
  realPath?: string
  digest: `sha256:${string}`
}

export interface ResolvedExportTarget {
  module: ResolvedFile
  exportName: string
}

export interface ClosureManifest {
  entries: Array<{
    role:
      | "runtime"
      | "declaration"
      | "manifest"
      | "resolution-input"
      | "literal-dynamic-chunk"
      | "generated"
    path: string
    digest: `sha256:${string}`
    transformDigest?: `sha256:${string}`
  }>
  dependencies?: unknown[]
  hazards?: unknown[]
  packages?: Array<{
    name: string
    version: string
    integrity: string
    filesManifestDigest: `sha256:${string}`
  }>
  digest: `sha256:${string}`
}

/** Full exact artifact resolution acquired independently by the host. */
export interface ResolvedImport {
  specifier: string
  importer: string
  requestedEntrypoint: string
  packageName: string
  packageVersion: string
  packageIntegrity: string
  packageRoot: string
  packageRealRoot?: string
  packageManifest: ResolvedFile
  runtime: ResolvedFile
  declarations: ResolvedFile
  runtimeTrace?: {
    branch: string
    steps?: Array<{ condition: string; target: string }>
  }
  declarationTrace?: {
    branch: string
    steps?: Array<{ condition: string; target: string }>
  }
  closure: ClosureManifest
  transform?: ResolvedFile
  exports?: Record<
    string,
    {
      runtime: ResolvedExportTarget
      declarations: ResolvedExportTarget
    }
  >
  authority: "host" | "typeFacts" | "standalonePackageResolver"
}

export interface AcceptedContractInput {
  /** Exact stable main schema-version-1 JSON text. */
  document: string
  /** Exact proof-issued receipt JSON text bound to the document bytes. */
  receipt: string
  import: ResolvedImport
}

/**
 * What the host resolved one imported specifier to, in its own installed tree.
 *
 * Accepted for compatibility and without effect: it fed the compiled-in
 * certified tier, retired by ADR 0228. Supply package behavior through
 * `acceptedContracts`.
 */
export interface InstalledPackage {
  /** The specifier as written in the source. */
  specifier: string
  name: string
  version: string
  /** The registry tarball's subresource integrity, from the host's lockfile. */
  integrity: string
  /**
   * The file this specifier resolves to, relative to the installed package
   * root — `dist/index.js` or `dist/index.d.ts`.
   */
  resolvedTarget: string
  /** The artifact snapshot root of the installed package's files. */
  snapshotRoot?: string
}

export interface CheckRequest {
  projectId: string
  /**
   * Dialect id ("solid-v2"). The wasm build cannot inspect a node_modules
   * tree, so an absent dialect means the default (solid-v2) rather than
   * detection.
   */
  dialect?: string
  generation: number
  sources: SourceFile[]
  /** TypeFacts v3 closure generated by a TypeScript host for these sources. */
  typeFacts: unknown
  /** Receipt-validated contracts. Missing imports remain uncertifiable. */
  acceptedContracts?: AcceptedContractInput[]
  /** Accepted for compatibility; has no effect (ADR 0228). */
  installedPackages?: InstalledPackage[]
  /** Accepted for compatibility; has no effect (ADR 0228). */
  exportConditions?: string[]
  /** Accepted for compatibility; has no effect (ADR 0228). */
  bundledContracts?: boolean
}

export interface PlanRequest {
  projectId: string
  /**
   * Dialect id ("solid-v2"). The wasm build cannot inspect a node_modules
   * tree, so an absent dialect means the default (solid-v2) rather than
   * detection.
   */
  dialect?: string
  generation: number
  sources: SourceFile[]
}

export interface PlanResponse {
  projectId: string
  generation: number
  /** TypeFacts v3 entity demands the host's TypeScript engine must answer. */
  demands: unknown[]
}

/** Runs the Oxc, Solid compiler, reactive IR, and solver pipeline in-process. */
export declare function checkSync(requestJson: string): string

/**
 * Runs the Oxc and Solid compiler passes only and returns the exact TypeFacts
 * demands those sources produce, as a JSON `PlanResponse`. A host answers them
 * with its own TypeScript engine and passes the resulting table to
 * `checkSync`, which repeats the syntax and compiler passes.
 */
export declare function planSync(requestJson: string): string
