export interface SourceFile {
  path: string
  source: string
  compilerOptions?: {
    moduleName: string
    generate: string
    hydratable?: boolean
    dev?: boolean
    effectWrapper?: string
    wrapConditionals?: boolean
    staticMarker?: string
    builtIns?: string[]
  }
}

export interface ResolvedImport {
  /**
   * UTF-8 **byte** offsets of the specifier string literal, quotes included,
   * into the source this same request carries. Not UTF-16 code units: the
   * source at this span is compared against `text`, and a mismatch is an error
   * rather than a refused contract, because forwarding TypeScript's own
   * positions unconverted is correct for ASCII and silently wrong after the
   * first non-ASCII character.
   */
  startByte: number
  endByte: number
  /** The specifier as written, after string-literal unescaping. */
  text: string
  /**
   * What the host's resolver recorded. An unrecognized value is refused rather
   * than guessed at.
   */
  resolution: "unresolved" | "relative" | "nodeModules" | "nonRelative"
  /**
   * The file the resolver selected, realpath-normalized. Empty or absent
   * exactly when `resolution` is `"unresolved"`; the two disagreeing is an
   * error, because an `unresolved` row is accepted by contract binding and is
   * the one claim here that could fail open.
   */
  resolvedPath?: string
  /**
   * `name` of the nearest package.json above `resolvedPath`. Absent or empty
   * means that manifest declares none, which is never read as a disagreement:
   * a published package routinely ships an unnamed `{"type":"module"}` file
   * beside its output.
   */
  packageName?: string
  packageManifest?: string
  /**
   * The package name the resolver itself recorded for this specifier, which can
   * differ from `packageName` for a subpath export or a nested install.
   */
  resolverPackageName?: string
}

export interface ResolvedImportFile {
  path: string
  /**
   * Every specifier in this file. An empty array says "this file imports
   * nothing", which is a different fact from omitting the file.
   */
  imports?: ResolvedImport[]
}

export interface CheckRequest {
  projectId: string
  /**
   * Dialect id ("solid-v2" or "solid-v1"). The wasm build cannot inspect a
   * node_modules tree, so an absent dialect means the default (solid-v2)
   * rather than detection.
   */
  dialect?: string
  generation: number
  sources: SourceFile[]
  /** TypeFacts v3 closure generated by a TypeScript host for these sources. */
  typeFacts: unknown
  /**
   * Where each import specifier resolves, as the host's own TypeScript engine
   * resolved it. A package contract describes one installed package, and this
   * is what binds a contract to the install a specifier actually resolves to.
   *
   * Omitting it binds package contracts by specifier *name*, which is what this
   * entry point has always done -- a documented limitation, not a weaker
   * analysis of the same request. Supplying it is all-or-nothing per specifier:
   * a file this field omits has no answer, and a contract is refused there
   * rather than falling back to the name.
   */
  resolvedImports?: { files?: ResolvedImportFile[] }
}

export interface PlanRequest {
  projectId: string
  /**
   * Dialect id ("solid-v2" or "solid-v1"). The wasm build cannot inspect a
   * node_modules tree, so an absent dialect means the default (solid-v2)
   * rather than detection.
   */
  dialect?: string
  generation: number
  sources: SourceFile[]
}

export interface PlanResponse {
  projectId: string
  generation: number
  /** TypeFacts v3 entity demands the host's TypeScript engine must answer. */
  demands: unknown[]
}

/** Runs the Oxc, Solid compiler, reactive IR, and solver pipeline in-process. */
export declare function checkSync(requestJson: string): string

/**
 * Runs the Oxc and Solid compiler passes only and returns the exact TypeFacts
 * demands those sources produce, as a JSON `PlanResponse`. A host answers them
 * with its own TypeScript engine and passes the resulting table to
 * `checkSync`, which repeats the syntax and compiler passes.
 */
export declare function planSync(requestJson: string): string
