//! Generated by `bun scripts/author-contracts.mjs build`. Do not edit.
//!
//! The authored contract index and the bytes of every document it names
//! (ADR 0198).

pub(super) const INDEX: &[u8] = include_bytes!("../../../../../pkg/contracts/authored/index.json");

pub(super) const OBJECTS: &[(&str, &[u8])] = &[
    (
        "objects/0e6e5e37d849689951edf7048f4d1b2fedbd07d94966f2b3504e884d9e158030.json",
        include_bytes!(
            "../../../../../pkg/contracts/authored/objects/0e6e5e37d849689951edf7048f4d1b2fedbd07d94966f2b3504e884d9e158030.json"
        ),
    ),
    (
        "objects/107fe960861bf7643949bcc646ce2acd30d19a53aa2c87e7fa883d1a97a48aae.json",
        include_bytes!(
            "../../../../../pkg/contracts/authored/objects/107fe960861bf7643949bcc646ce2acd30d19a53aa2c87e7fa883d1a97a48aae.json"
        ),
    ),
    (
        "objects/86f782fcdb16d39a7179b1f23069cbe61207c083982285e19727ada82de79cdb.json",
        include_bytes!(
            "../../../../../pkg/contracts/authored/objects/86f782fcdb16d39a7179b1f23069cbe61207c083982285e19727ada82de79cdb.json"
        ),
    ),
    (
        "objects/89c2b8ef6df67b0415be0c94e3cea3c1d62892954b34c343bcc29cd18ec320cd.json",
        include_bytes!(
            "../../../../../pkg/contracts/authored/objects/89c2b8ef6df67b0415be0c94e3cea3c1d62892954b34c343bcc29cd18ec320cd.json"
        ),
    ),
    (
        "objects/d5516ac20ba841c40cdda5b44060df22e1ff094d2f38fdaa4e7d2f8aa2b2fd78.json",
        include_bytes!(
            "../../../../../pkg/contracts/authored/objects/d5516ac20ba841c40cdda5b44060df22e1ff094d2f38fdaa4e7d2f8aa2b2fd78.json"
        ),
    ),
];
