//! Generated by `bun scripts/author-contracts.mjs`. Do not edit.
//!
//! The authored contract index and the bytes of every document it names
//! (ADR 0198).

pub(super) const INDEX: &[u8] = include_bytes!("../../../../../pkg/contracts/authored/index.json");

pub(super) const OBJECTS: &[(&str, &[u8])] = &[];
