[package]
name = "solid-reactive-ir"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
solid-dialect = { path = "../solid-dialect" }
solid-facts = { path = "../solid-facts" }
typefacts.workspace = true
thiserror.workspace = true
